name: coffee_logs
channels:
    - conda-forge
dependencies:
    - python=3.7.12
    - pip
    - pip:
        - boxsdk==2.14.0
    - numpy=1.20.3
    - pandas=1.3.5
    - pyyaml=6.0
    - requests=2.31.0
