name: coffee_logs
channels:
    - conda-forge
dependencies:
    - python=3.11
    - pip
    - pip:
        - boxsdk==3.9.1
    - numpy=1.26.0
    - pandas=2.1.1
    - pyyaml=6.0.1
    - requests=2.31.0
